services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./
        target: /app
  bdd:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: john
